url=https://www.saucedemo.com/
mail.smtp.host=smtp.gmail.com
mail.smtp.port=465
mail.from=lawma195.infinity@gmail.com
mail.password=jcyu enxk gxeo wgbb
mail.to=elkaytlau7@gmail.com
mail.smtp.auth=true
mail.smtp.starttls.enable=true